version: '3.4'

services:
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DEEPFACE_HOME: /node/scripts
    ports:
      - 3001:3001
    volumes:
      - ./server/public/images:/node/public/images
      - ./server/scripts:/node/scripts
  webapp:
    image: webapp
    build:
      context: web_app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
