version: '3.4'

services:
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    volumes:
      - ./server/public/images:/node/public/images
  webapp:
    image: webapp
    build:
      context: web_app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  face:
    image: face
    build:
      context: face
      dockerfile: ./Dockerfile
    environment:
      DEEPFACE_HOME: /usr/src/app
    ports:
      - 5000:5000